apiVersion: v1
kind: Pod
metadata:
  name: tailscale-forwarder
spec:
  initContainers:
  - name: sysctler
    image: busybox
    securityContext:
      privileged: true
    command: ["/bin/sh"]
    args:
      - -c
      - sysctl -w net.ipv4.ip_forward=1
    resources:
      requests:
        cpu: 1m
        memory: 1Mi
  containers:
  - imagePullPolicy: Always
    name: tailscale
    image: "{{IMAGE_TAG}}"
    volumeMounts:
    - name: state
      mountPath: /var/lib/tailscale
    env:
    - name: USERSPACE
      value: "false"
    - name: AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: tailscale-auth
          key: AUTH_KEY
          optional: true
    - name: DEST_IP
      value: "{{DEST_IP}}"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
