apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscale
  namespace: network
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tailscale
  serviceName: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      initContainers:
      - name: sysctl-buddy
        image: busybox:1.29
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args:
          - -c
          - sysctl -w net.ipv4.ip_forward=1
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      containers:
      - imagePullPolicy: Always
        name: tailscale
        image: tailscale
        env:
        - name: AUTH_KEY
          value: ""
        - name: DEST_IP
          value: ""
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
