apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscale
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  serviceName: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      initContainers:
      - name: sysctler
        image: busybox
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args:
          - -c
          - sysctl -w net.ipv4.ip_forward=1
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      containers:
      - imagePullPolicy: Always
        name: tailscale
        image: "{{IMAGE_TAG}}"
        volumeMounts:
        - name: state
          mountPath: /var/lib/tailscale
        env:
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: AUTH_KEY
              optional: true
        - name: DEST_IP
          value: "{{DEST_IP}}"
        - name: ROUTES
          value: "{{ROUTES}}"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: state
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  updateStrategy:
    type: RollingUpdate
