apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscale
  namespace: network
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tailscale
  serviceName: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      containers:
      - imagePullPolicy: Always
        name: tailscale
        image: ubuntu
        args:
        - while true; do sleep 30; done;
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        command:
        - /bin/bash
        - -c
        - --
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Always
      schedulerName: default-scheduler
      hostNetwork: true
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
