apiVersion: v1
kind: Service
metadata:
  labels:
    app: tailscale
  name: tailscale
  namespace: network
spec:
  clusterIP: None
  selector:
    app: tailscale
  sessionAffinity: None
  type: ClusterIP
